### ISSUE TITLE
Move to currentMonth(props not working) from any date

### ISSUE THREAD

**Issue by iit2008047** [christopherdro/react-native-calendar#113]
Scenario: I switch selected date to next month, I have a button which updates my selected date to today. Now it should auto scroll to the current month and select today's date. 

I have tried with currentMonth prop but it doesnt work auto scroll to current month, but the selectedDate changes to today 

So, basically i need to update the current month to the selected month .. @christopherdro

**Comment by nolan-m** [comment]
I had this problem as well.   I saw that it was fixed in master, but not in the latest release (0.10.0).  The last release to npm was in December.  I'm not sure the release schedule for this project, but it would be nice to get a new release for this feature.


In the meantime, I set my `package.json` dependency to use the latest commit in master 

```
"react-native-calendar": "github:christopherdro/react-native-calendar#af3d38e",
```

**Comment by christopherdro** [comment]
This is in 11.0 now.
