### ISSUE TITLE
monthNames not working

### ISSUE THREAD

**Issue by basequatro** [christopherdro/react-native-calendar#129]
monthNames={customMonthNames} is not working after last commits.

**Comment by LMestre14** [comment]
is your customMonthNames an array of 12 string elements?

**Comment by hungdev** [comment]
i get same error. it not working.  @LMestre14  , could you set month is upcase?

**Comment by LMestre14** [comment]
@hungdev could you post the error that you have pls

**Comment by basequatro** [comment]
@LMestre14 yes 12 string array, was working before, maybe its related to line 310 after last commit.
https://github.com/christopherdro/react-native-calendar/blob/master/components/Calendar.js

**Comment by hungdev** [comment]
@LMestre14  
i have customMonthNames like this:
const customMonthNames = ['JANUARY', 'FREBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE',
  'JUNLY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER']
then add monthNames={customMonthNames} to `<Calendar />`
but it not change month to upcase

**Comment by LMestre14** [comment]
@basequatro in my case I send the exact same thing, I even have arrays for differente langs, so that it shows the months by the devices system language.

And I think you're right, the only way that the topbar should display your custom month is by having {localizedMonth} {this.state.currentMoment.year()}
because, if in the last commit it has {this.state.currentMoment.format(this.props.titleFormat)}
you're not able to change it :/ because it will always print by the moment.js format

@christopherdro

**Comment by christopherdro** [comment]
Fixed via https://github.com/christopherdro/react-native-calendar/commit/9dae00d84aae28d5289e099eebf6fe41c0f93733

Will release a new version soon.
