### ISSUE TITLE
Show full year instead of month?

### ISSUE THREAD

**Issue by akondo06** [christopherdro/react-native-calendar#90]
Hi,
I have a case where I need to show events in a full year to be similar to the html version (client wants it).

I was gonna try and write a calendar myself and I stumbled upon this.
Is it possible to show 12 months one under another in a ScrollView ?

Regards,
Akondo

**Comment by christopherdro** [comment]
@akondo06 This library doesn't currently support a full year view.

Not sure how the UI would work for this anyway since each month will be to small to interact with.
You could follow the default behavior of iOS and Android by having the months in the year view be a simple touchable image that then navigates you to the calendar component for that month.
